version: "3"

networks:
  re_cluster:
    driver: nat
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

services:
  # Primary
  primary:
    build: 
      context: .
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name:
      primary
    ports:
      - 6379:6379
    command:
      ["redis-server",  "c:\\conf\\redis.conf"]
    volumes:
      - ${CONFIG_DIR}\conf\primary:c:\conf:ro
      - ${CONFIG_DIR}\data\6379:c:\data:rw
    networks:
      re_cluster:
        ipv4_address: 192.168.1.11

  # Replica 1
  replica1:
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: 
      replica1
    ports:
      - 6380:6380
    command: 
      ["redis-server",  "c:\\conf\\redis.conf"]
    volumes:
      - ${CONFIG_DIR}\conf\replica1:c:\conf:ro
      - ${CONFIG_DIR}\data\6380:c:\data:rw
    networks:
      re_cluster:
        ipv4_address: 192.168.1.12
    depends_on:
        - primary

  # Replica 2
  replica2:
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: 
      replica2
    ports:
      - 6381:6381
    command: 
      ["redis-server",  "c:\\conf\\redis.conf"]
    volumes:
      - ${CONFIG_DIR}\conf\replica2:c:\conf:ro
      - ${CONFIG_DIR}\data\6381:c:\data:rw
    networks:
      re_cluster:
        ipv4_address: 192.168.1.13
    depends_on:
        - primary

#
# EOF (2024/07/05)
#